# Generated by Django 5.1 on 2024-10-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("rollno", models.IntegerField(primary_key=True, serialize=False)),
                ("subject1", models.IntegerField()),
                ("subject2", models.IntegerField()),
            ],
        ),
    ]
